### ISSUE TITLE
Plug-in makes Sticky Menu to not work

### ISSUE THREAD

**Issue by Ceaco** [JoryHogeveen/off-canvas-sidebars#100]
## Describe the bug

Hello, when i activate the Plug-in, the sticky header does not works, when it is disabled, the header works ust fine.

## Expected behavior

I expected that the menu would stay over the sidebar and still work.

## Specifications

  - Plugin Version: 0.5.6
  - WordPress Version: 5.5.1.
  - Other plugins installed: Bold Builder, BoldThemes WordPress Importer, Cost Calculator, Custom My Account for Woocommerce, Meta Box, Shopscape Plugin, WooCommerce, WooCommerce Customizer, WooSidebars, YITH WooCommerce Wishlist
  - Theme: Shopscape 
  - Browser: Mozila Firefox, Chrome, Opera
  - URL of where the bug occurs: https://pettech.ro, https://pettech.ro/produse

**Comment by JoryHogeveen** [comment]
Have you read and followed the installation guide?
There is a compatibility setting for sticky elements

**Comment by Ceaco** [comment]
Yes, I have read the installation guide but i couldn't find anywhere compatibility settings for sticky elements.

**Comment by JoryHogeveen** [comment]
See plugin settings page. If you choose CSS2 positioning it will most likely be fixed.

**Comment by Ceaco** [comment]
Thank you, this fixed the issue. You are the best!

**Comment by JoryHogeveen** [comment]
Great!
Also, please consider leaving a nice review, it will help the plugin grow :)
https://wordpress.org/support/plugin/off-canvas-sidebars/reviews/

Thanks! Jory
