### ISSUE TITLE
Links on mobile not working or going to the wrong page when clicked

### ISSUE THREAD

**Issue by msbt** [JoryHogeveen/off-canvas-sidebars#101]
## Describe the bug
Topic pretty much describes it all, I have a navigation element in OCS and desktop works fine, but on mobile the links either don't open at all (sidebar closes though) or go to a wrong page (mostly the link below the one that's clicked).

## Steps to reproduce the behavior:
1. Go to **redacted** on desktop and mobile (dev tools also work)
2. Click on burger
3. Try to open a link
4. Encounter issue

## Expected behavior
Open the link that was clicked

## Specifications

  - Plugin Version: v0.5.6
  - WordPress Version: 5.5.1
  - Other plugins installed:
  - Theme: understrap child
  - Browser: all
  - URL of where the bug occurs: see above
  - Location of hook placement (header.php and footer.php): as suggested, plugin says it works

## Additional context
No idea why this is happening, tried all options and in the element inspector everything looks fine. Tried all compatibility settings but no dice. Since the site launched yesterday I'm in a bit of a pickle 🙄

**Comment by JoryHogeveen** [comment]
Hi @msbt 
This is probably the same issue as #82 
Am I correct that this happens on a iOS device?

**Comment by msbt** [comment]
Hi @JoryHogeveen, not necessarily, this happens on all devices (you can even replicate it with the developer tools in any browser), the smaller the screen, the more you miss.

**Comment by JoryHogeveen** [comment]
Hi @msbt 
Could to try to disable closing the sidebar once clicked on a link?

**Comment by msbt** [comment]
Oh wow, I can't believe it was that easy, that did the trick. Thanks a lot!

**Comment by JoryHogeveen** [comment]
Hi @msbt 
No problem! I'm still looking into why this is happening, it has something to do with event bubbling (I thought it was iOS only).
I might end up adding a small timeout before triggering the sidebar close event.
