### ISSUE TITLE
My website is displaying "2014" as content for the hamburger menu instead of the flat line.

### ISSUE THREAD

**Issue by mycmedia** [JoryHogeveen/off-canvas-sidebars#102]
## Description
https://drainfx.com/

If you take a look at the sidebar menu, it is showing the character code "2014" instead of the line or the value.

## Specifications

  - Plugin Version: 0.5.6
  - WordPress Version: 5.6.1
  - Other plugins installed: 
  - Theme:  Divi 4.9.0
  - Browser: Chrome

**Comment by JoryHogeveen** [comment]
Hello @mycmedia 

It's installed but doesn't render properly. Please read the installation instructions.
https://github.com/JoryHogeveen/off-canvas-sidebars/wiki/Theme-setup

It also looks like you've been testing with other off-canvas solutions, correct?

Cheers, Jory

**Comment by JoryHogeveen** [comment]
Closing due to no reply, feel free to re-open if you still need help!
