### ISSUE TITLE
Scape Theme 1.4.2 is incompatible 

### ISSUE THREAD

**Issue by delegacz** [JoryHogeveen/off-canvas-sidebars#103]
## Describe the bug
when using wp_body_open and wp_footer in the configuration of the plugin, Scapes build-in mobile menu breaks and no longer works as it should. It is open by default when it should be closed and the trigger to close no longer works

## Steps to reproduce the behavior:
1. Install [Scape](https://themeforest.net/item/scape-multipurpose-wordpress-theme/23250017?gclid=Cj0KCQjwsLWDBhCmARIsAPSL3_0aKLAw1pve8sYl1kVts7reP_iPgP-LX5OpvZDAsSFiw-86kGFJ7psaAnzPEALw_wcB) theme
2. Create a Mobile Menu
3. Install Off-Canvas Sidebars
4. Use wp_body_open and wp_footer in plugin configuration
5. echo sidebar shortcode anywhere on the page

## Screenshot
![error_23](https://user-images.githubusercontent.com/47157858/113882343-1f9a1b00-97b5-11eb-8882-4a24ea40d8bb.jpg)

## Specifications

  - Plugin Version: 0.5.7
  - WordPress Version: 5.7
  - Theme: Scape
  - Browser: Chrome
  - Location of hook placement (header.php and footer.php) add_action on hook woocommerce_before_shop_loop with a custom function that echoes the shortcode there

**Comment by delegacz** [comment]
As an update: everything works fine when using CSS2 mode.

**Comment by JoryHogeveen** [comment]
Hi @delegacz 

This is a limitation in browsers when using transform with fixed positioned items.
Unfortunately I can't fix this in the default Slidebars code, that is why I created the CSS2 legacy option.
Closing issue!

Cheers, Jory
