### ISSUE TITLE
0.5.7 - Concatentation breaking class names.

### ISSUE THREAD

**Issue by TomSequitur** [JoryHogeveen/off-canvas-sidebars#104]
## Describe the bug
As of Version 0.5.7, `ocs-sidebar-active- + sidebar_id` and `ocs-sidebar-location- + sidebar.side` are concatenated without a separating space, breaking both class names.

## Steps to reproduce the behavior:
1. Create new sidebar with Location set to Right on OCS v0.5.7.
2. Assign a widget to sidebar area.
3. Action sidebar.
4. See concatenation issue: in my case `ocs-sidebar-active-ocs-mobile-navocs-sidebar-location-right`.

## Expected behavior
Class names concatenated with a space separating: `ocs-sidebar-active-ocs-mobile-nav ocs-sidebar-location-right`.

## Screenshots
![screenshot](https://user-images.githubusercontent.com/1839722/116151189-24a60800-a699-11eb-96fb-4520afb28e8b.jpg)

## Specifications
  - Plugin Version: 0.5.7
  - WordPress Version: 5.7.1
  - Other plugins installed: ACF Pro, Debug Bar, Gravity Forms, Regenerate Thumbnails, Simple Custom Post Order, WPFront Scroll Top
  - Theme: Custom, _'s base
  - Browser: Firefox 88.0
  - URL of where the bug occurs: local install only
  - Location of hook placement (header.php and footer.php): immediately after `<body>` opens and immediately before `wp_footer()`.

## Additional context
- Issue looks to me to appear at line 472 of `off-canvas-sidebars.js`: 
`$html.addClass( 'ocs-sidebar-active ocs-sidebar-active-' + sidebar_id + 'ocs-sidebar-location-' + sidebar.side );`

Many thanks for a fantastic plugin, and apologies if this has already been reported.  I looked but didn't see any similar issues.

Kind regards,
Tom

**Comment by AllWorkNoPlay-95** [comment]
I am having the same issue, i can confirm what TomSequitur described.
Please fix it asap, it's breaking functionality on our site.

**Comment by JoryHogeveen** [comment]
Thanks guys! Merged for the next release :)
