### ISSUE TITLE
Error:     1: Off-Canvas Sidebars are not direct children of the HTML body tag.  Please check your hooks and priorities.

### ISSUE THREAD

**Issue by 2021benders** [JoryHogeveen/off-canvas-sidebars#106]
Hi Jory,
## Describe the bug
I am using an AVADA child theme with woocommerce.  I would like to put a widget of subcategories in the off canvas.  Expecting the user to hit a button to see the subcategories.

I tried putting the code using your simple setup instructions both headers and footers.
The site is bendersshoes.com but you cannot see the storefront yet.  I can send you the files or whatever you need to see my issue.

Thank you!

**Comment by JoryHogeveen** [comment]
Hi @2021benders 

I've looked at the link you've posted and it seems that your implementation of the simple setup is incorrect.
The sidebars are rendered within the site container, not outside.
Did you also update your hooks in the settings?

Also, isn't Avada already compatible with the default WordPress hooks? (see basic setup).

In any case, I know Avada is a very large theme with various features so it might be difficult to fully integrate it with this plugin.
