### ISSUE TITLE
Can't view certain pages when logged into wordpress/plugin is installed/in Safari

### ISSUE THREAD

**Issue by cariirwin** [JoryHogeveen/off-canvas-sidebars#107]
## Describe the bug
When all 3 of these conditions are met....
1. The Off-Canvas Sidebars plugin is activated 
2. I am logged into my wordpress site
3. I am using Safari...
- My Simple Job Board jobs are fully blank
- My events page created by The Events Calendar is fully blank

 

## Steps to reproduce the behavior:
1. Use Safari
2. Log into your wordpress site
3. Install Off-Canvas Sidebars plugin plus either The Events Calendar or Simple Job board and create an entry
4. Try to preview the job listing and/or the auto-created /events page (*not* the single event page)
5. Deactivate the Off-Canvas Sidebars plugin and see if you can preview

## Expected behavior
I expected to be able to see my events page and my job listings

## Specifications

  - Plugin Version: 0.5.7
  - WordPress Version: 5.8
  - Other plugins installed: Many...
  - Theme: Salient
  - Browser: Safari
  - URL of where the bug occurs: You have to be logged in to see the issue, but: 
  1. https://edz.wpengine.com/events/
  2. https://edz.wpengine.com/applications/practice-period-2021/
  
  - Location of hook placement (header.php and footer.php)

**Comment by JoryHogeveen** [comment]
Hi @cariirwin 

I checked your page's and can see all content. As you've mentioned you need to log in in order to see the error, this actually tells me it's not related to this plugin but most likely a bug in some other content being rendered on the page if you are an admin.

Unfortunately I do not have Safari so I cannot test on that browser since it is only supported for iOS.
Even though, since the bug only happens when you are logged in I doubt the browser would make any difference.

For now there isn't much I can do, please fully revalidate your HTML markup or allow me to log in to a dev environment where you can reproduce the bug.

Cheers, Jory

**Comment by cariirwin** [comment]
Hi Jory,
Here is a login to the environment. If you take a look, you'll see the
error goes away if I deactivate the Off-Canvas Sidebar plugin:
https://edz.wpengine.com/wp-admin/
Test_HR
zonsop-sogcuv-2Jiqxy

The plugins it's conflicting with are used here on the site:
1. The Events Calendar Pro:
https://edz.wpengine.com/wp-admin/edit.php?post_type=tribe_events
2. Simple Job Board:
https://edz.wpengine.com/wp-admin/edit.php?post_type=jobpost

Thanks for looking into this!

Best,
Cari

**Comment by JoryHogeveen** [comment]
Hello @cariirwin 

The login data you've provided seems to be incorrect.
Also, please do not share these on GitHub (if you reply to this email you will also share it on GitHub).
Could you email me on info@keraweb.nl?

Cheers, Jory

**Comment by JoryHogeveen** [comment]
Hello @cariirwin 

Thank your for the corrected login.
I've checked your page and found that the HTML markup isn't correct.
It looks like your theme already supports various slideout's similar to those of this plugin.
Also, the admin bar is located inside the site wrapper, this should be a direct child of the `<body>` tag. This is most likely a theme issue.
Secondly, it looks like you are using a fixed menu. In order this to work you'll need to set the compatibility mode to "Legacy CSS" (CSS2).

Let me know if this helps!

Cheers, Jory

**Comment by JoryHogeveen** [comment]
Note, I just changed the compatibility mode to Legacy CSS and it already works a lot better.
