### ISSUE TITLE
Compatible theme hooks

### ISSUE THREAD

**Issue by wp-capmatch** [JoryHogeveen/off-canvas-sidebars#112]
I'm using this theme:
https://my.seventhqueen.com/docs/seeko/welcome

And need to add the correct hooks to the Off Canvas Sidebars plugin.

Existing hooks used by the theme are:
https://my.seventhqueen.com/docs/buddyapp/buddyapp-theme-hooks/

**Comment by JoryHogeveen** [comment]
Hi @wp-capmatch 

Please contact the theme developer about these hooks!
They might even support the default hooks (`wp_body_open` and `wp_footer`).
https://github.com/JoryHogeveen/off-canvas-sidebars/wiki/Theme-setup

Cheers, Jory
