### ISSUE TITLE
Add nofollow to OCS tigger links

### ISSUE THREAD

**Issue by inspiredearth** [JoryHogeveen/off-canvas-sidebars#116]
## Description

**Describe the solution you'd like**
I would like to suggest adding either `rel="nofollow"` or `data-nofollow` to the trigger links. Without these, Google's SEO analysis for the site will deduct a few points due to there being links without a valid `href`. As shown here:

![image](https://github.com/JoryHogeveen/off-canvas-sidebars/assets/667395/cecdb870-6b1b-442e-a9af-ef1e4c09ba1f)

**Is your feature request related to a problem? Please describe.**
The issue is that Google's PageSpeed and SEO analysis doesn't like links without an `href` attribute. It might have minimal real world impact, but since the solution is so simple, and it will stop Google deducting a few percentage of SEO score, it might as well be implemented.

**Comment by JoryHogeveen** [comment]
Fixed in 0.5.8
