### ISSUE TITLE
Off-canva side bar

### ISSUE THREAD

**Issue by Jharperrobo1896** [JoryHogeveen/off-canvas-sidebars#118]
Hello,

i have downloaded and activated the off-canva plug in. i am using a divi theme but it isnt showing to use.

i want to see menus on a mobile and tablet not just pc

**Comment by JoryHogeveen** [comment]
Hi @Jharperrobo1896 

Is it working on desktop? If so, then you'll probably just need to add triggers on mobile to trigger the off-canvas sidebars.

Cheers, Jory

**Comment by Jharperrobo1896** [comment]
Hello,

I had deleted a code after finding a forum online - that worked a treat

Thank you
________________________________

**Comment by JoryHogeveen** [comment]
Good to hear you've solved it, Cheers!
