### ISSUE TITLE
Menu Overwrite when you create a 2 or more Off-Canvas Sidebars

### ISSUE THREAD

**Issue by SMaximo** [JoryHogeveen/off-canvas-sidebars#37]
## Expected Behavior
I try to use differents off canvas menu into a WordPress site

## Actual Behavior
When you create a second Off Canvas Sidebar, this menu overwrites all other Off Canvas, except their style.

Example 1st menu:
![captura de pantalla 2017-09-14 a las 11 08 05](https://user-images.githubusercontent.com/31953494/30421448-16f53b26-993d-11e7-888e-d7ded6b63f2c.png)

Example 2nd menu
![captura de pantalla 2017-09-14 a las 11 08 17](https://user-images.githubusercontent.com/31953494/30421451-17e93e9c-993d-11e7-87db-2763a8ca9afc.png)

Menus configuration
![captura de pantalla 2017-09-14 a las 11 09 37](https://user-images.githubusercontent.com/31953494/30421531-539eaf62-993d-11e7-8e35-564f30c08786.png)

Off Canvas Sidebars Created
![captura de pantalla 2017-09-14 a las 11 06 38](https://user-images.githubusercontent.com/31953494/30421462-1d16eafe-993d-11e7-99fc-05b847dbfbb0.png)

If the last Off Canvas Sidebar created is disabled, all others will be disabled too.
## Steps to Reproduce the Problem

  1.Create Off Canvas Menu
  1.Assign the Canvas Menu
  1.Create another Canvas Menu

## Specifications

  - Plugin Version:0.4
  - WordPress Version:4.8.1
  - Other plugins installed: Visual Composer, Ultimate Addons for Visual Composer, WooCommerce
  - Theme: The7
  - Browser: Google Chrome, Firefox

**Comment by JoryHogeveen** [comment]
Hi @SMaximo 

Thank you for your bug report. I've added a fix in the dev branch!
See #40
