### ISSUE TITLE
Hooks on my theme OceanWP

### ISSUE THREAD

**Issue by sofiaspain** [JoryHogeveen/off-canvas-sidebars#46]
Hi, Jory:  I´m totally new to hooks.  My theme (OceanWP) has a hook extension.  I placed the text that you give in the BEFORE CONTENT hook and in the AFTER CONTENT hook.  I also added an Off-Canvas Sidebar menu item.   
 
The result is that the menu item appears, but nothing happens when I click on it.
Also, the hook text literally appears on the page.  No side bar. 

Where am I going wrong?  Ocean WP has a long list of hooks.  I tried BEFORE CONTENT and AFTER CONTENT.  Should I try different ones?

Thank you in advance for your help.
Sofia

 ## Expected Behavior

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Plugin Version:
  - WordPress Version:
  - Other plugins installed:
  - Theme:
  - Browser:

**Comment by JoryHogeveen** [comment]
Hi @sofiaspain 

Every theme works different so it's allways hard to say. Do you have a link so I can take a look? It might be a JavaScript incompatibility with the scripts from your theme or plugins.

Thanks, Jory

**Comment by knightknight** [comment]
Works in OceanWP fine, needs CSS styles though. Just need to use the right hook! 

```php
// Off-Canvas Sidebars
function offcanvas_oceanwp_before() {
	do_action('website_before');
}
add_filter( 'ocean_before_outer_wrap', 'offcanvas_oceanwp_before' );

function offcanvas_oceanwp_after() {
 do_action('website_after');
}
add_filter( 'ocean_after_outer_wrap', 'offcanvas_oceanwp_after' );
```

**Comment by knightknight** [comment]
> overwrite the hooks

Awesome, didn't think of that!!. 👍
