### ISSUE TITLE
Sidebar closes when user scrolls it with touch

### ISSUE THREAD

**Issue by d--j** [JoryHogeveen/off-canvas-sidebars#48]
## Expected Behavior

The Sidebar should be able to be scrolled without being closed thereafter.

## Actual Behavior

When a user scrolls the sidebar with touch and she happens to end the scroll on a link (`<a>` tag) then the sidebar closes.

## Steps to Reproduce the Problem

  1. Go to https://www.mbi-geodata.com/en/ with a mobile browser or in mobile device emulation
  1. Open the off canvas mobile navigation
  1. Scroll the off canvas navigation with touch (or on mobile device emulation with clicking and dragging the mouse) – _not with the scroll bar or with scroll functionality of your mouse_.
  1. The off canvas sidebar closes

## Specifications

  - Plugin Version: 0.4.2
  - WordPress Version: 4.9
  - Other plugins installed: admin-menu-editor advanced-export-for-wp-wpmu bwp-google-xml-sitemaps black-studio-tinymce-widget bulk-content-creator cms-tree-page-view content-aware-sidebars uk-cookie-consent display-posts-shortcode flowpaper-lite-pdf-flipbook gravityforms multisite-cloner multisite-language-switcher newsletter nextend-smart-slider3-pro nextgen-flex-slider-template nextgen-gallery nextgen-mbi nextgen-gallery-plus off-canvas-sidebars pods really-simple-ssl responsive-lightbox shariff shortcode-menu tinymce-advanced tinymce-and-tinymce-advanced-professsional-formats-and-styles user-switching w3-total-cache widget-clone wordpress-popular-posts wp-piwik yith-footer-banner wordpress-seo
  - Theme: not public
  - Browser: All Touch-Enabled (tested in Android 7, iOS 11 and Chrome with mobile device emulation)

## Pointers

This code is probably responsible for this behaviour: 
https://github.com/JoryHogeveen/off-canvas-sidebars/blob/72a2d33a7985ebeff3f8cb4f22e44935bc53b674/js/off-canvas-sidebars.js#L389-L394

Why do you include `touchend` in the list of events there? Doesn't all touch enabled browser emulate the `click` event?

**Comment by JoryHogeveen** [comment]
Hi @d--j 

Sorry for my late reply. I'm aware of this issue and will release a minor update a.s.a.p. An extra enhancement is that this behavior will be a global setting, over-writable for each sidebar.
I will notify you when I push it to GitHub!
For now you can remove those lines of code.

> Why do you include touchend in the list of events there? Doesn't all touch enabled browser emulate the click event?

Unfortunately no. Some browsers do not trigger the `click` event for touch devices.

Regards, Jory

**Comment by JoryHogeveen** [comment]
Hi @d--j 
If you are able, please check the PR for the new 0.5 version!
It's currently tagged as `0.5-dev` so you will still be notified of any live updates through WP.
Thanks, Jory

**Comment by d--j** [comment]
Hi @JoryHogeveen 
looks like [0.5-dev](https://github.com/JoryHogeveen/off-canvas-sidebars/archive/b943d4dd9d09f53432f5904c212ceb350dc8244d.zip) solves this issue. Thanks very much.

**Comment by JoryHogeveen** [comment]
Hi @d--j 
Great, I'll close this issue and will release 0.5 a.s.a.p.!

Thanks for testing and if you have the time, please leave review, it will help this plugin grow 🙂
https://wordpress.org/support/plugin/off-canvas-sidebars/reviews/

Cheers, Jory
