### ISSUE TITLE
ocs-site white space

### ISSUE THREAD

**Issue by overcatbe** [JoryHogeveen/off-canvas-sidebars#60]
## Describe the bug
White space after content.
Firstly - very much thank you for this awesome plugin. :)

## Steps to reproduce the behavior:
All time white space after content with fixed height as described here https://github.com/adchsm/Slidebars/issues/10

## Specifications

  - Plugin Version: newest
  - WordPress Version: newest
  - Other plugins installed:
  - Theme: storefront
  - Browser: all of them

**Comment by JoryHogeveen** [comment]
Hi @overcatbe,

Can you share a link so I can take a look at you site structure and CSS?

Thanks, Jory

**Comment by overcatbe** [comment]
it's a site in making so ugly as of now :)
https://www.croatian-apartments.com/?page_id=180
thanks!

**Comment by overcatbe** [comment]
the trigger shows on mobile width. :D

**Comment by JoryHogeveen** [comment]
Hi @overcatbe,

It seems your structure is incorrect.
You current HTML shows this:
```html
<body>
   <div id="page">
      Site content
   </div>
   <div id="ocs-site">
      Canvas container
   </div>
</body>
```

While it should show this:
```html
<body>
   <div id="ocs-site">
      <div id="page">
         Site content
      </div>
   </div>
</body>
```

Please check if your installation is using the correct hooks and the hooks are placed correctly.
See: [installation guide](https://github.com/JoryHogeveen/off-canvas-sidebars/wiki/Theme-setup)

Let me know! Jory

**Comment by JoryHogeveen** [comment]
Oh, since you are using Storefront, see this page for compatible hooks:
https://github.com/JoryHogeveen/off-canvas-sidebars/wiki/Compatible-theme-hooks#storefront-woocommerce

**Comment by overcatbe** [comment]
indeed! i need to learn to read! thanks!

**Comment by JoryHogeveen** [comment]
No problem! If you run into any problems let me know!

PS: if you like the plugin, please consider leaving a nice review, it will help the plugin grow
https://wordpress.org/support/plugin/off-canvas-sidebars/reviews/#new-post

**Comment by overcatbe** [comment]
indeed! i need to learn to read! thanks!
