### ISSUE TITLE
PLUGGIN DOESN'T WORK WITH AURUM THEME (Minimalist WooCoomerce Shopping Theme)

### ISSUE THREAD

**Issue by AngelEspejo** [JoryHogeveen/off-canvas-sidebars#69]
Hello, the plugin does not work with my theme 'Aurum - minimalistisc shopping theme'. I think it's something related to the "hook name" although I do not know exactly what this is.
Can you help me? I would love to have the plugin.
or in case it is not due to "hook name", can you confirm me why it does not work?

**Comment by JoryHogeveen** [comment]
Hello @AngelEspejo,

I'm not familiar with that theme but have you read the installation instructions?
https://github.com/JoryHogeveen/off-canvas-sidebars/wiki/Theme-setup

If you did, do you have a link for me to check?

Regards, Jory

**Comment by AngelEspejo** [comment]
Ok!
After several attempts testing the instructions, finally, I see my sidebar. It has many visible failures, but I think they will be solved with CSS.
I'll try.

thanks for the help and for the plugin.

**Comment by JoryHogeveen** [comment]
Hi @AngelEspejo,
No problem, let me know if you need further help. I'll close this issue for now.
Regards, Jory
