### ISSUE TITLE
Off-canvas sidebar on Rehub Theme for filter woocommerce products on mobile devices

### ISSUE THREAD

**Issue by amit1200** [JoryHogeveen/off-canvas-sidebars#72]
Hi,
Your plugin is very good. I'm looking for an off-canvas sidebar on Rehub Theme for Woocommerce products filters on "Mobile Devices". How can i use your plugin on my Rehub theme. {i'm not a techy guy}.

**Comment by JoryHogeveen** [comment]
Hello @amit1200,

Sorry for my late reply, I'm on holiday at the moment.
I'm not familiar with the Rehub theme but have you read the installation instructions? See the wiki page!

Regards, Jory
