### ISSUE TITLE
problem with zephyr theme

### ISSUE THREAD

**Issue by mr2od** [JoryHogeveen/off-canvas-sidebars#74]
## Description
its not working on the zephyr theme

## Specifications

  - Plugin Version: latest version on reposity
  - WordPress Version: 5.2.2
  - Other plugins installed: yes, but i disabled all other plugins and test it , still not working .
  - Theme: zephyr version 6.3
  - Browser: chrome and firefox

**Comment by JoryHogeveen** [comment]
Hello @mr2od,

Have you read the installation instructions?
https://github.com/JoryHogeveen/off-canvas-sidebars/wiki/Theme-setup

Regards, Jory

**Comment by mr2od** [comment]
hello my friend 

yes i,ve install it step by step from wiki / theme setup but still not working 
it,s ok when i disable the theme and active default theme but on the ZEPHYR theme it,s not working on click action .

**Comment by JoryHogeveen** [comment]
Could you share a link so I can take a look? Could be a JavaScript conflict.

**Comment by mr2od** [comment]
http://mr2od.ir/hi-tech/

its left side of the header 
i use a HTML shortcode to show the button 

( i dont add any css yet )

**Comment by mr2od** [comment]
did you made any progress ?

**Comment by JoryHogeveen** [comment]
Hello @mr2od,

By looking at the code the installation isn't correct.
What type of installation did you use?
And which hooks have to used in the settings of this plugin?

**Comment by mr2od** [comment]
hello again my friend 

i,ve used Simple theme setup .

and this is the HTML code that generated by off-canvas shortcode generator : 

`<button class="ocs-trigger ocs-toggle ocs-toggle-header"><span class="icon dashicons `dashicons-menu-alt3"></span></button>`

did i made a mistake ?

**Comment by JoryHogeveen** [comment]
The shortcode is fine but the setup itself is incorrect.
- What changes did you made to your theme and **what are your settings?**
- Did you create a child theme before you made the changes?

**Comment by mr2od** [comment]
hello again 

can you check my dashboard  with the admin access ?
i can add you as admin account and sent you details 
just sent me your email .
i did everything right , but still not working , even i,ve update the zephyr to the latest version .

**Comment by JoryHogeveen** [comment]
Hello @mr2od,

> i did everything right

I've seen the output code and the installation simply isn't correct. It looks like you didn't made the required changes to your theme files for this plugin to work.

**Please answer my questions:**
* What changes did you made to your theme and what are your settings?
* Did you create a child theme before you made the changes? (if you didn't, updating zephyr theme probably removed your changes).

If you want me to help you I do need you to help me understand where the installation might went wrong.
Simply saying "its not working on the zephyr theme" in your bug-report won't help.

**Comment by JoryHogeveen** [comment]
Closing this issue due to no reply. Feel free to reopen if you still require help with this.
