### ISSUE TITLE
Background overlay + header toggle

### ISSUE THREAD

**Issue by vonsa** [JoryHogeveen/off-canvas-sidebars#78]
Hi Jory,

1. Is het mogelijk om een overlay in te stellen voor alles buiten de slidebar, wanneer deze actief wordt?
2. Kan het kloppen dat als ik in de header klik, er geen toggle getriggered wordt voor de slidebar? Klikken in de rest van de layout triggered wel.

Inspectie, implementatie of een aantal coderegels zou nice zijn!

![slidebar](https://user-images.githubusercontent.com/60012821/72634328-a1a4e680-395a-11ea-9660-fd8168857da1.png)

Overigens hier de hooks om de slidebar in te stellen voor het Divi thema:
- et_before_main_content
- wp_footer

Ik weet niet of het met custom slider inhoud bereikt kan worden, maar als je een post (weet niet of post hiervoor werkt) o.i.d. toe zou kunnen voegen dan zou dit mogelijk met een pagebuilder ontworpen kunnen worden, wat een hoop mogelijkheden creëert.

Al het beste,

Coen

**Comment by JoryHogeveen** [comment]
Hoi @vonsa 

> Is het mogelijk om een overlay in te stellen voor alles buiten de slidebar, wanneer deze actief wordt?

Niet via de plugin maar het lijkt me relatief eenvoudig om dit via CSS/JS zelf te maken.

> Kan het kloppen dat als ik in de header klik, er geen toggle getriggered wordt voor de slidebar? Klikken in de rest van de layout triggered wel.

In dat geval denk ik dat de hooks toch niet kloppen. Ik zie namelijk de `page-container` als eerst child van de `<body>` en dit klopt niet. Wanneer worden deze precies uitgevoerd binnen de header.php en footer.php? De standaard WP hooks `wp_body_open` zit niet in Divi?

Cheers, Jory

**Comment by vonsa** [comment]
Hey Jory,

Dankje voor je reactie.

Blijkbaar heeft Divi hier geen hooks voor.

Nu heb ik header.php en footer.php gekopieerd vanuit mijn Divi thema folder naar mijn Divi child thema folder.

Dit zijn de locaties waar ik jouw php regels geplaatst heb:

**header.php**
<body <?php body_class(); ?>>
<?php do_action('website_before'); ?>

**footer.php**
</div> 
<?php do_action('website_after'); ?>

@ instelling van jouw plugin gebruik ik website_before en website_after @ hooks velden. 
Front-end inschakelen staat ook aangevinkt.

Nu werkt je slidebar helemaal niet.

Wat doe ik verkeerd?

En geeft deze aanvullende code geen problemen op mijn multisitenetwerk wanneer ik je slidebar niet gebruik op een andere subsite met hetzelfde thema?

Al het beste,

Coen

**Comment by JoryHogeveen** [comment]
Ha Coen,

Kun je een link sturen naar je pagina?
`header.php` lijkt me goed maar ik vermoed dat de `footer.php` nog niet correct is.
Heb je de actie nét voor `wp_footer()` geplaatst?

Cheers, Jory

**Comment by vonsa** [comment]
Dank voor je snelle reactie Jory,

Ja klopt net voor wp_footer:
/div> 
?php do_action('website_after'); ?
?php wp_footer(); ?

Dit is de eerste keer dat ik iets aanpas in header.php & footer.php van child thema, weet niet of er nog meer bij komt kijken.

Onderstaand de link naar de pagina! Je vind een **click me!** knop in de eerste sectie onder de header.
https://vonsanetwerk.nl/theboxvoorstel/?ucp-access=bddbdbc4

**Comment by JoryHogeveen** [comment]
Aan je pagina te zien staan de hooks nog niet juist. De canvas wordt nu namelijk helemaal niet meer geladen.
Kun je een export maken van de instellingen en die hier plakken?

> En geeft deze aanvullende code geen problemen op mijn multisitenetwerk wanneer ik je slidebar niet gebruik op een andere subsite met hetzelfde thema?

Nee hoor, een actie doet niks zolang er geen code gebruik van maakt.

**Comment by vonsa** [comment]
Uiteraard, hier de export:

[off-canvas-sidebars-settings.txt](https://github.com/JoryHogeveen/off-canvas-sidebars/files/4108376/off-canvas-sidebars-settings.txt)

> Nee hoor, een actie doet niks zolang er geen code gebruik van maakt.

Oké dat is mooi dankjewel voor de info.

**Comment by JoryHogeveen** [comment]
Hmm dat lijkt ook goed te zijn.. kun je mij tijdelijk toegang geven tot de admin zo dat ik even kan kijken? (heb je het bewerken van theme bestanden aan staan?)
**Graag login sturen naar info@keraweb.nl en niet hier plaatsen!**
