### ISSUE TITLE
Open/Close buttons not available

### ISSUE THREAD

**Issue by ssstofff** [JoryHogeveen/off-canvas-sidebars#85]
All works fine, after editing the header.php & footer.php, the extra code is rendered when doing element inspector

Except, the sidebar isn't showing. Nor there is an open/close button.

WP: 5.4
GenesisWP: 3.3.1
Used ChildTheme: Genesis Sample Master

The Css has a display:none on that container and that's it. No other errors. The trigger buttons are also not loaded. I suppose this is the problem.

Please contact me DM for site access (staging) + admin login

**Comment by JoryHogeveen** [comment]
My first guess is that the installation isn't working correctly.
Please send site info to info@keraweb.nl so I can take a look.

**Comment by ssstofff** [comment]
my mistake. didnt see the documentation that close/show triggers needs to created manually ... which is excellent.

**Comment by JoryHogeveen** [comment]
Ah right, yep I intended this to be manual so you can place them wherever you want in the way you want yourself.
If you are building a theme you can use the PHP API so the locations are hard-coded.
