### ISSUE TITLE
Invalid HTML markup in off-canvas sidebars: widgets wrapped in li elements as children of a div

### ISSUE THREAD

**Issue by diegocanal** [JoryHogeveen/off-canvas-sidebars#88]
## Describe the bug
In off-canvas sidebars the widgets are output wrapped in `<li>` HTML elements, but not as children of a `<ul>`, `<ol>`, or `<menu>` element –or the obsolete `<dir>` element–, which is invalid HTML markup ([reference in MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li)). 

## Steps to reproduce the behavior:
1. Add a off-canvas sidebar.
2. Add a couple of widgets inside the sidebar.
3. Inspect the code in dev tools to see the `<li>` elements wrapping the widgets.

## Expected behavior
In my opinion, the widgets should not be output wrapped in `<li>` elements, `<div>` seems to me semantically more neutral and appropriate. 

## Screenshots
![Screenshot 2020-05-12 at 18 47 40](https://user-images.githubusercontent.com/3908213/81722354-8cac1000-9481-11ea-9f78-d62e3b80800a.png)

## Specifications

  - Plugin Version: 0.5.4
  - WordPress Version:5.4.1
  - Other plugins installed: none
  - Theme: Twenty NineteenVersión: 1.5
  - Browser: Chrome version 81.0.4044.138 (Official Build) (64-bit)
  - URL of where the bug occurs: staging site not public
  - Location of hook placement: 
     - header.php: directly after `<body <?php body_class(); ?>`
     - footer.php: directly after the site content, before `<?php wp_footer(); ?>`)

**Comment by JoryHogeveen** [comment]
Hello @diegocanal 

You can change this through the `ocs_register_sidebar_args` filter to change it according to your theme.
WordPress by default uses `<li>` elements for widgets (no idea why...) so I'm trying not to change to much in WordPress defaults.
However, in this case I do agree that it might be better for me to overwrite this default since the sidebars will never be list items in my case I suppose.

**Comment by JoryHogeveen** [comment]
I've added a new commit to the `dev` branch (next update) that will fix this:
https://github.com/JoryHogeveen/off-canvas-sidebars/commit/c1f81ffaf1bf3f1ff7157aaa43479b100c91486e

**Comment by diegocanal** [comment]
Thanks @JoryHogeveen for your superfast reaction.

I'm not a programmer so figuring out how to solve it using the filter would have taken me a while. Your new commit has saved me a lot time.

I love your plugin. Keep up with the good work!

**Comment by JoryHogeveen** [comment]
Hi @diegocanal 
No problem! And thanks for your review!
Cheers, Jory
