### ISSUE TITLE
is off-canvas-sidebar forcing vertical outputs?

### ISSUE THREAD

**Issue by sayantandas** [JoryHogeveen/off-canvas-sidebars#90]
## Describe the bug
i am using YITH product filters with the off-canvas-sidebar. I see the attribute filters are showing as lists, one in each line instead of displaying horizontally 

## Steps to reproduce the behavior:
1. Go to 'https://tagprive.adwaitatech.com/shop'
2. Click on 'Filters'
3. Check 'Filter by Color' and 'Filter by size'

## Expected behavior
Expected behaviour is to display the filter horizontally

## Specifications

  - Plugin Version: 0.5.5
  - WordPress Version: 5.4.1
  - Other plugins installed: YITH Filter
  - Theme: Themify Shoppe
  - Browser: Chrome
  - URL of where the bug occurs: https://tagprive.adwaitatech.com/shop
  - Location of hook placement (header.php and footer.php): content_start

## Additional context
Tested with Oceanwp theme's inbuilt off-canvas theme the attributes show up horizontally

**Comment by JoryHogeveen** [comment]
Hello @sayantandas 

This is not an error or bug, it's an incompatibility with your theme CSS and the YITH plugin.
This plugin does not add any CSS for styling the inner elements of a slidebar, that is up to your theme.

In your case there is a CSS selector in your theme that prevents the list elements from floating beside eachother.
See styles.css line 3382:
```
.widget li {
	margin: 0;
	padding: 0 0 1em;
	list-style: none;
	clear: both; <<<<<<<<<<<<<
}
```

You'll need to overwrite this for your sidebars.
