### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by temiloluwaalabi** [JoryHogeveen/off-canvas-sidebars#93]
## Description
A clear and concise description about the issue.
i dont know how to use it

## Specifications

  - Plugin Version: 0.5.5
  - WordPress Version: latest
  - Other plugins installed: woocommerce
  - Theme: astra free theme
  - Browser: chrome

**Comment by JoryHogeveen** [comment]
Hello @temiloluwaalabi 

Have you read the installation instructions?
https://github.com/JoryHogeveen/off-canvas-sidebars/wiki

**Comment by temiloluwaalabi** [comment]
Yes

**Comment by JoryHogeveen** [comment]
Then what don't you understand?

**Comment by temiloluwaalabi** [comment]
the sidebar isnt showing on the page

**Comment by JoryHogeveen** [comment]
Once you've correctly made the installation the sidebars are rendered outside of the canvas (hence the name, off-canvas). You can create triggers/buttons to make them appear.
This can be done through the widget, a menu item or a shortcode.

**Comment by temiloluwaalabi** [comment]
alright. let me try

**Comment by temiloluwaalabi** [comment]
hello, will i create a menu before i can use it

**Comment by JoryHogeveen** [comment]
That depends on where you want the button to be. If you want that to be in a menu, then yes.
This plugin is only meant as the framework for off-canvas sidebars.

You'll have to decide for yourself where you want to buttons/triggers to be and what styles (CSS) you want your sidebars to have.

**Comment by JoryHogeveen** [comment]
Closing topic. If you still having troubles feel free to re-open this topic!
