### ISSUE TITLE
wp_body_open hook is not fired error.

### ISSUE THREAD

**Issue by Inlay** [JoryHogeveen/off-canvas-sidebars#98]
## My off canvas Sidebar for Filter was working fine until yesterday but I am receiving this error now. How to solve it?
I tried using wp_body_open() but it did not work. 

## Specifications

  - Plugin Version: 0.5.6
  - WordPress Version: 5.4.2
  - Other plugins installed:
  - Theme: Wordpress 2020 theme
  - Browser: Irrelevant

**Comment by JoryHogeveen** [comment]
Hello @Inlay 

Can you confirm the following:
- Your cache is fully cleared (browser cache and site/cdn cache if applicable)
- This error is happening with al other plugins disabled
- You hook configuration is correct (see settings page)

I also just found an issue with the validator tool. The check for the canvas attribute isn't correct.

Cheers, Jory

**Comment by JoryHogeveen** [comment]
See validator tool fix here: https://github.com/JoryHogeveen/off-canvas-sidebars/commit/115804e1068bd9881b7fbb5f063f7163502009fb

**Comment by Inlay** [comment]
Hello,
I reinstalled offcanvas sidebar plugin and it started working.

It happened after I uninstalled one plugin i suppose.

Will it happen again if i remove any plugin ?


Best Regards

**Comment by JoryHogeveen** [comment]
Hi @Inlay 

If your configuration and theme stays the same it **_should_** be fine.
However, as there are thousands of plugins, I cannot say for sure it will work with all of them.

Cheers, Jory
